### ISSUE TITLE
Add a link to the About page (see #17) that defines CV and MOE

### ISSUE THREAD

**Issue by aprilhirsh** [216software/Profiles#15]
This is an important feature to have in this first iteration of the tool because it helps the user better understand the data. In the SWPA and Prov Plan versions of the site (https://profiles.ucsur.pitt.edu/profiles/county/42003/overview/ and http://profiles.provplan.org/profiles/state/44/overview/) there is a small " +/- " icon next to indicators derived from ACS data. The icon displays the margin of error (MOE) when the user hovers over it.

![moe cv hover](https://cloud.githubusercontent.com/assets/7606957/17700939/c7664f4c-6395-11e6-9b82-d3010115448c.JPG)

We would like the icon to display the MOE and the CV when the user hovers over it. If we want to get fancy (if not too difficult), it could be cool if the estimate also turned a color based on the quality indicated by the CV when hovering over the icon. I don't think this is worth it if it's difficult, but if you think it's not too tough it could be nice to play with.

MOE for indicators have an "m" preceding the rest of the indicator label. For example:

_grent1014 = median gross rent, 2010-2014
m_grent1014 = median gross rent, MOE, 2010-2014
cv_grent1014 = median gross rent, Coefficient of Variation, 2010-2014

I'm attaching our data dictionary for your use here.

[CNP Dashboard Varlist_2016Jan27.xlsx](https://github.com/216software/Profiles/files/420376/CNP.Dashboard.Varlist_2016Jan27.xlsx)

**Comment by bormesh** [comment]
@aprilhirsh 

I've got color coding working for this. Right now, for CV, I have the following breakdown:

< 15 green (good)
< 61 yellow (ok)
&gt; 61 red (bad)

What should the color codes be for the MOE variable?

Thanks!

**Comment by bormesh** [comment]
Also, instead of a hover, I've switched to a button click -- hover's are nice but won't work on mobile. This way all users will still be able to see the data.

**Comment by aprilhirsh** [comment]
Great! MOEs don't need coloration.

**Comment by aprilhirsh** [comment]
I like the functionality here, but it definitely makes the site look messier. Is there any way to simplify the "compare" link and move it to the outer edge, same with the CV/MOE ? It looks like in SWPA and Prov Plan, both are in their own column to the far right of the table.

**Comment by bormesh** [comment]
Check out this page to talk about during meeting:

http://profiles.216software.com/#/stabilization?location_uuid=4ce7e0a3-9c63-4e21-a9dc-20b3ccf10346

**Comment by bormesh** [comment]
todo: Add a link to the About page (see #17) that defines CV and MOE

**Comment by bormesh** [comment]
Added a link to the popup that connects to Data Sources section (MOE & CV) of the About page.

**Comment by bormesh** [comment]
Going to close this out. Link added to CV/MOE popup that links to about section.
