### ISSUE TITLE
Change location button to become "set location" button

### ISSUE THREAD

**Issue by aprilhirsh** [216software/Profiles#19]
Change the name of the "change location" button to "set location."
Other improvements to make it more obvious to the user that this is the first step in accessing information would be helpful.

**Comment by aprilhirsh** [comment]
How about we default to displaying the city-level info (City of Cleveland geography)? I think that will help people recognize that the need to set another location of interest to view more data.

**Comment by bormesh** [comment]
Added Cleveland City as the default location, and leaving 'Change Location' as is, since it should now make sense in context.

**Comment by bormesh** [comment]
Closing this for now. At the moment, we default to 'Cleveland' as our initial location, so we'll leave 'Change Location' instead of 'Set Location'
