### ISSUE TITLE
Add a download PDF feature

### ISSUE THREAD

**Issue by mw44118** [216software/Profiles#4]
Just like with the CSV feature,  we should generate these after data is loaded, not when people request them.

**Comment by bormesh** [comment]
When converting to PDF, indicators marked with an asterisk with extra text need to be visible in the printed PDF

**Comment by bormesh** [comment]
Also, when printing to pdf we should show the additional data (ie CV & MOE)

**Comment by bormesh** [comment]
Download pdfs added to tabbed pages, as well as indicator comparison page.
