### ISSUE TITLE
Add map link next to each indicator that opens popup

### ISSUE THREAD

**Issue by mw44118** [216software/Profiles#5]
In the popup, show neighboring neighborhoods, colorized by the selected indicator. 

Allow choice of time periods if multiple ones exist.

**Comment by aprilhirsh** [comment]
I wouldn't say "show neighboring neighborhoods" I'd say show all geographies available at that level. So, if the user is looking at the Cudell neighborhood, and click on the map icon, s/he can now see that indicator for all neighborhoods. If the user is looking at the Fairfax Renaissance Development Corp Service Area, and s/he clicks on the map button, s/he can see that indicators for all service areas. 

Also add download components, this will be the main way a user can download one indicator for all neighborhoods.

In addition to adding multiple time points where available, add geography selection, so the user, if looking at service area, can switch to neighborhood and visa versa.

**Comment by bormesh** [comment]
Updated on profiles.216software.com -- Added a 'compare' link next to the indicator name so that the indicator values can be compared against other locations and on a map
