### ISSUE TITLE
Investigate progress tab - rental statistics not most recent -- please let us know which data point is not good

### ISSUE THREAD

**Issue by mw44118** [216software/Profiles#7]
The rental statistics might not be the most recent.

**Comment by aprilhirsh** [comment]
The data in the progress tab is not visible right now, but I believe it was from last years file. I'm adding the two data files from this year in case it's helpful to you. 
[CNP_Indicators_Service_Area_for_2016_final.xlsx](https://github.com/216software/Profiles/files/420338/CNP_Indicators_Service_Area_for_2016_final.xlsx)
[CNP_Indicators_spa_ for_2016_final.xlsx](https://github.com/216software/Profiles/files/420339/CNP_Indicators_spa_.for_2016_final.xlsx)

**Comment by tsuichan** [comment]
The statistics displayed on the Community Profiles site are correct.  You just need to change all the column headings from 2009-2013 to 2010-2104.

**Comment by bormesh** [comment]
Dates have now been corrected.
