### ISSUE TITLE
Investigate "% income less than $10,00" -- Do rate's also have associated CVs? 

### ISSUE THREAD

**Issue by mw44118** [216software/Profiles#8]
It is missing its CV statistic.

**Comment by bormesh** [comment]
Hmm -- this one is interesting. 

From their spreadsheet, % / rates don't have associated CV's with them. Did they say that these should have associated CV's as well?

We're currently displaying the CV for 'Income less than $10,000' -- perhaps a single location is missing?

**Comment by mw44118** [comment]
I need to email April and Tsui with links to the github issues.  Then maybe
we can get them to explain it better in the issue comments.

**Comment by bormesh** [comment]
Sounds good

On Tue, Aug 16, 2016 at 7:42 AM, W. Matthew Wilson <notifications@github.com

> wrote:
> 
> I need to email April and Tsui with links to the github issues. Then maybe
> we can get them to explain it better in the issue comments.
>

**Comment by bormesh** [comment]
I believe this is the spreadsheet column 'cv_hhincls10k' -- I'll get the CV's added to the rates for all of these.

**Comment by aprilhirsh** [comment]
Hello! I know in an older version of the file, we did not have CVs for the number and percent of population by household income indicators. But the latest file with ACS 2010-2014 data does have CVs for those indicators. The indicators are named as follows: numbers are hhincls10k1014, hhinc10kto15k1014, etc; percents/rates are _hhincls10k1014, _hhinc10kto15k1014, etc.; CVs are cv_hhincls10k1014, cv_hhinc10kto15k1014, etc.

**Comment by tsuichan** [comment]
All CVs for percentages/rates start with "cv_".  CVs for numbers start with "cv" without underscore.
