### ISSUE TITLE
Almost all vars starting with _ should be indented and italic

### ISSUE THREAD

**Issue by mw44118** [216software/Profiles#9]
Check styling on provplan site.

Except for median sales price, all vars starting with _ should be styled.

**Comment by tsuichan** [comment]
Only the following four variables with "_" should not be indented.  
_medinc2000
_medinc1014
_grent2000
_grent1014

The variable names for median sales price in the armslength file don't start with "_".  These variables already have the right name convention and they should not be indented.

**Comment by bormesh** [comment]
Thanks for the response, Tsui -- I think I've caught all the right ones.
